services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/work
    command: "tail -F anything"
    ports:
      - 5678:5678
    stdin_open: true
    tty: true
    env_file:
      - .devcontainer/.env
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [ utility, compute, video ]
